#!/bin/bash

python rl_search.py \
    --save_dir game_data/br \
    --weight1 ../models/sad_2p_models/sad_2.pthw \
    --weight2 ../models/my_models/br_sad_six_1_3_6_7_8_12/model_epoch1000.pthw \
    --sad_legacy 1,0 \
    --player_name sad_2,br_sad_six_1_3_6_7_8_12 \
    --data_type test \
    --game_seed 2 \
    --seed 2 \
    --burn_in_frames 5000 \
    --replay_buffer_size 100000 \
    --rl_rollout_device cuda:1 \
    --bp_rollout_device cuda:1 \
    --train_device cuda:0 \
    --belief_device cuda:0 \
    --rollout_batchsize 8000 \
    --num_thread 1 \
    --batchsize 128 \
    --num_epoch 1 \
    --epoch_len 5000 \
    --num_samples 50000 \
    --skip_search 0 \
    --verbose 1 \
    --ad_hoc 1 \
    --upload_gcloud 1 \
    --save_game 1 \

#python rl_search.py \
    #--save_dir exps/test \
    #--weight1 ../models/sad_2p_models/sad_2.pthw \
    #--weight2 ../models/my_models/br_sad_six_1_3_6_7_8_12/model_epoch1000.pthw \
    #--sad_legacy 1,0 \
    #--player_name sad_2,br_sad_six_1_3_6_7_8_12 \
    #--data_type test \
    #--game_seed 2 \
    #--seed 2 \
    #--burn_in_frames 500 \
    #--replay_buffer_size 1000 \
    #--rl_rollout_device cuda:1 \
    #--bp_rollout_device cuda:1 \
    #--rollout_batchsize 500 \
    #--num_thread 1 \
    #--num_game_per_thread 20 \
    #--train_device cuda:0 \
    #--batchsize 128 \
    #--num_epoch 1 \
    #--epoch_len 1 \
    #--belief_device cuda:0 \
    #--num_samples 1 \
    #--maintain_exact_belief 1 \
    #--search_exact_belief 1 \
    #--skip_search 0 \
    #--verbose 1 \
    #--ad_hoc 1 \
